### ISSUE TITLE
How to write Step from Surf ?

### ISSUE THREAD

**Issue by selvakarna** [LaughlinResearch/AFEM#2]
How to write Step from Mesh ?

**Comment by trelau** [comment]
I'm not sure I understand what you are trying to achieve? If you have a mesh, the only way to write a STEP file might be to convert each triangle into a Face and then export as a shape, but I doubt that's what you really want? Can you be more specific?

**Comment by selvakarna** [comment]
Hi @trelau ,

   Yes, I want to write a STEP file from MESH details using Python Scripts . so how to 

Write STEP file ? 

1. what are the details needed to write STEP file using Python?

**Comment by trelau** [comment]
This example https://github.com/LaughlinResearch/AFEM/blob/master/examples/exchange_step_write.py will show you the most basic example of writing a STEP file via the AFEM interface.

The biggest challenge in your case might be converting the mesh to an OCCT shape representation. Once you have a shape, writing that shape to a STEP file is straightforward.

**Comment by selvakarna** [comment]
Hi @trelau ,

   Can you share OCCT shape ,samples or any link?

**Comment by selvakarna** [comment]
Hi @trelau ,

   Can you share OCCT shape ,samples or any link?

**Comment by selvakarna** [comment]
Hi @trelau ,

   Can you share OCCT shape ,samples or any link?

**Comment by selvakarna** [comment]
Hi @trelau , How to export SUrf to step ?

**Comment by trelau** [comment]
Once you have a Face (which is derived from a Shape), the same example above shows how export a STEP file.
