### ISSUE TITLE
ModuleNotFoundError: No module named 'OCCT' ? when i import  afem.exchange ?

### ISSUE THREAD

**Issue by selvakarna** [LaughlinResearch/AFEM#3]
ModuleNotFoundError: No module named 'OCCT' ? when i import  afem.exchange ?

**Comment by trelau** [comment]
What installation instructions did you follow? Can you provide the exact steps to reproduce the issue? More information is needed to diagnose the issue.

**Comment by selvakarna** [comment]
Hi @trelau , can not activate occt  using Conda in linux:

   I have use following commands to activate OCCT:

      conda activate occt


* But its not activate?

**Comment by trelau** [comment]
how did did you install AFEM? how did you install its dependencies?

depending on your platform...pyOCCT may or may not be available...so you may need to build everything from sources following instructions from the various projects

**Comment by selvakarna** [comment]
Hi @trelau , How to install pyOCCT using Python PIP Commands ?

**Comment by trelau** [comment]
it's not available on pip....i'd suggest using conda to install dependencies like OCCT, then build pyOCCT from sources on your local machine
